# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-07-07 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.ORGANIZATIONS_ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guid", models.CharField(editable=False, max_length=40)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("version", models.CharField(default="v0", max_length=3)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("report_type", models.CharField(max_length=50)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_reportrequest",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="modified_reportrequest",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="requested_reports",
                        to=settings.ORGANIZATIONS_ORGANIZATION_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-created_at"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        )
    ]
