# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-09-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='report_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
