# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-09-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_reportrequest_report_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportrequest',
            name='is_processed',
        ),
    ]
