# -*- coding: utf-8 -*-
# Generated by Django 2.2.8 on 2020-02-25 18:01

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(
            settings.ORGANIZATIONS_ORGANIZATION_MODEL
        ),
        ('customers', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanerRecord',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                ('returned_on', models.DateTimeField(blank=True, null=True)),
                ('is_lost', models.NullBooleanField()),
                ('penalty', django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    'created_by',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_loanerrecord',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'inventory_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='loaner_records',
                        to='inventory.LoanerInventoryItem',
                    ),
                ),
                (
                    'last_modified_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='modified_loanerrecord',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                ('kbb_serial_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.FloatField(default=0.0)),
                (
                    'created_by',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_orderline',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'inventory_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='order_line',
                        to='inventory.RepairInventoryItem',
                    ),
                ),
                (
                    'last_modified_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='modified_orderline',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Replacement Spare',
                'verbose_name_plural': 'Replacement Spares',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                (
                    'password',
                    models.CharField(default='NA', max_length=100, null=True),
                ),
                (
                    'initial_operating_system',
                    models.CharField(default='NA', max_length=100, null=True),
                ),
                ('status', models.CharField(max_length=100)),
                ('coverage_type', models.CharField(max_length=100)),
                ('repair_type', models.CharField(max_length=100)),
                (
                    'issue_reported_by_customer',
                    models.CharField(max_length=500),
                ),
                ('device_condition', models.CharField(max_length=500)),
                ('expected_service_cost', models.FloatField(default=0.0)),
                ('expected_hardware_cost', models.FloatField(default=0.0)),
                (
                    'accessories',
                    models.CharField(default='NA', max_length=500),
                ),
                (
                    'required_upgrades',
                    models.TextField(default='NA', max_length=500),
                ),
                ('expected_delivery_time', models.DateTimeField()),
                ('is_backup_required', models.BooleanField(default=False)),
                (
                    'reference_number',
                    models.CharField(max_length=50, unique=True),
                ),
                (
                    'is_standby_device_required',
                    models.BooleanField(default=False),
                ),
                ('first_escalation_after', models.DateTimeField()),
                ('second_escalation_after', models.DateTimeField()),
                ('final_escalation_after', models.DateTimeField()),
                ('closed_on', models.DateTimeField(null=True)),
                (
                    'closed_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='closed_tickets',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_ticket',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'currently_assigned_to',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='assigned_tickets',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'customer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='tickets',
                        to='customers.Customer',
                    ),
                ),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='tickets',
                        to='devices.Device',
                    ),
                ),
                (
                    'last_modified_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='modified_ticket',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'loaner_devices',
                    models.ManyToManyField(
                        through='tickets.LoanerRecord',
                        to='inventory.LoanerInventoryItem',
                    ),
                ),
                (
                    'orderlines',
                    models.ManyToManyField(
                        through='tickets.OrderLine',
                        to='inventory.RepairInventoryItem',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='tickets',
                        to=settings.ORGANIZATIONS_ORGANIZATION_MODEL,
                    ),
                ),
                (
                    'sla',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='tickets',
                        to='slas.SLA',
                    ),
                ),
                (
                    'subscribers',
                    models.ManyToManyField(
                        blank=True,
                        related_name='subscribed_tickets',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                (
                    'cash',
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    'cheque',
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    'online_payment',
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ('cc', models.FloatField(blank=True, default=0.0, null=True)),
                (
                    'online_payment_reference_number',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    'reference_number',
                    models.CharField(max_length=50, unique=True),
                ),
                ('towards', models.CharField(blank=True, max_length=100)),
                ('online_payment_date_time', models.DateTimeField(null=True)),
                ('note', models.CharField(blank=True, max_length=2400)),
                ('is_cancelled', models.BooleanField(default=False)),
                (
                    'created_by',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_voucher',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'last_modified_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='modified_voucher',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'ticket',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vouchers',
                        to='tickets.Ticket',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
            },
        ),
        migrations.CreateModel(
            name='UploadContent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                ('file', models.FileField(upload_to='')),
                (
                    'upload_type',
                    models.CharField(
                        choices=[
                            ('Ticket', 'Ticket'),
                            ('Delivery', 'Delivery'),
                        ],
                        max_length=255,
                    ),
                ),
                ('description', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                (
                    'content_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.ContentType',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_uploadcontent',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'last_modified_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='modified_uploadcontent',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SerializableOrderLine',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.FloatField(default=0.0)),
                (
                    'created_by',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_serializableorderline',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'last_modified_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='modified_serializableorderline',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'ticket',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='serializable_order_lines',
                        to='tickets.Ticket',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Serializable Replacement Spare',
                'verbose_name_plural': 'Serializable Replacement Spares',
            },
        ),
        migrations.AddField(
            model_name='orderline',
            name='ticket',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='order_lines',
                to='tickets.Ticket',
            ),
        ),
        migrations.AddField(
            model_name='loanerrecord',
            name='ticket',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='loaner_records',
                to='tickets.Ticket',
            ),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                ('parameter', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                (
                    'created_by',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_feedback',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'last_modified_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='modified_feedback',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'ticket',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedbacks',
                        to='tickets.Ticket',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Customer Feedback',
                'verbose_name_plural': 'Customer Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='DevicePartReport',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                ('part', models.CharField(max_length=50)),
                (
                    'initial_status',
                    models.CharField(default="Didn't Check", max_length=50),
                ),
                (
                    'final_status',
                    models.CharField(default="Didn't Check", max_length=50),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_devicepartreport',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'last_modified_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='modified_devicepartreport',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'ticket',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='device_part_reports',
                        to='tickets.Ticket',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Device Part Report',
                'verbose_name_plural': 'Device Part Reports',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                ('actual_service_cost', models.FloatField(default=0.0)),
                ('actual_hardware_cost', models.FloatField(default=0.0)),
                (
                    'device_pickup_time',
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    'gsx_reference_number',
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ('actual_issue', models.CharField(max_length=1000)),
                ('action_taken', models.CharField(max_length=1000)),
                ('final_operating_system', models.CharField(max_length=50)),
                ('gsx_repair_type', models.CharField(max_length=50)),
                ('outward_condition', models.CharField(max_length=1000)),
                (
                    'reference_number',
                    models.CharField(max_length=50, unique=True),
                ),
                (
                    'customer_signature',
                    models.ImageField(null=True, upload_to='signatures'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_delivery',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'last_modified_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='modified_delivery',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'ticket',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='delivery',
                        to='tickets.Ticket',
                    ),
                ),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                ('value', models.CharField(max_length=2000)),
                (
                    'created_by',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_comment',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'last_modified_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='modified_comment',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'ticket',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='tickets.Ticket',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
