# -*- coding: utf-8 -*-
# Generated by Django 2.2.8 on 2020-05-10 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_delivery_comptia_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSXInfo',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                ('gsx_reference_number', models.CharField(max_length=30)),
                ('gsx_repair_type', models.CharField(max_length=50)),
                ('comptia_code', models.CharField(max_length=50)),
                (
                    'created_by',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_gsxinfo',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'last_modified_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='modified_gsxinfo',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'ticket',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='gsx_informations',
                        to='tickets.Ticket',
                    ),
                ),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
