# Generated by Django 2.2.8 on 2020-05-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_gsxinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='comptia_code',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='gsx_reference_number',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='gsx_repair_type',
        ),
    ]
