# Generated by Django 2.2.10 on 2020-05-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20200512_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket', to='customers.Customer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket', to='devices.Device'),
        ),
    ]
