# Generated by Django 2.2.13 on 2020-11-16 09:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_unit_part_reports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='delivery',
            name='unit_part_reports',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
