# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-11-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("tickets", "0008_auto_20201116_0906")]

    operations = [
        migrations.AlterModelOptions(
            name="loanerrecord",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Loaner Record",
                "verbose_name_plural": "Loaner Records",
            },
        ),
        migrations.AlterModelOptions(
            name="orderline",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Replacement Spare",
                "verbose_name_plural": "Replacement Spares",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
            },
        ),
        migrations.RemoveField(model_name="delivery", name="reference_number"),
    ]
