# Generated by Django 2.2.13 on 2020-11-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20201118_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-created_at'], 'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
    ]
