# Generated by Django 2.2.13 on 2020-11-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20201119_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-id'], 'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='gsxinfo',
            options={'ordering': ['-id'], 'verbose_name': 'GSX Info', 'verbose_name_plural': 'GSX Info'},
        ),
        migrations.AlterModelOptions(
            name='loanerrecord',
            options={'ordering': ['-id'], 'verbose_name': 'Loaner Record', 'verbose_name_plural': 'Loaner Records'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ['-id'], 'verbose_name': 'Replacement Spare', 'verbose_name_plural': 'Replacement Spares'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-id'], 'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_signature',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
