# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-11-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0012_auto_20201129_1425")]

    operations = [
        migrations.AddField(
            model_name="serializableorderline",
            name="part_number",
            field=models.CharField(max_length=50, null=True),
        )
    ]
