# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-12-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0013_serializableorderline_part_number")]

    operations = [
        migrations.AddField(
            model_name="loanerrecord",
            name="customer_signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="customer_signatures/loaner_record"
            ),
        )
    ]
