# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-12-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0015_ticket_repair_classification")]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="box_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="gsx_coverage_option",
            field=models.CharField(default="BATTERY", max_length=100),
        ),
        migrations.AddField(
            model_name="ticket",
            name="loaner_stock_unavailable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="mark_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="request_review_by_apple",
            field=models.BooleanField(default=False),
        ),
    ]
