# Generated by Django 2.2.13 on 2020-12-13 15:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20201213_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='component_issues',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
