# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-12-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0017_ticket_component_issues")]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="coverage_option",
            field=models.CharField(max_length=100, null=True),
        )
    ]
