# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-12-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0018_orderline_coverage_option")]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="from_consigned_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="pricing_option",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
