# Generated by Django 2.2.13 on 2020-12-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_componentissue_reproducibility'),
        ('tickets', '0019_auto_20201214_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='componenet_issue',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_line', to='devices.ComponentIssue'),
        ),
    ]
