# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-12-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0022_voucher_sla")]

    operations = [
        migrations.AlterField(
            model_name="gsxinfo",
            name="comptia_code",
            field=models.CharField(max_length=200),
        )
    ]
