# Generated by Django 2.2.13 on 2020-12-30 14:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_auto_20201229_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer_feedback',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
