# Generated by Django 2.2.13 on 2021-01-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_delivery_customer_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='inward_time',
            field=models.DateTimeField(null=True),
        ),
    ]
