# Generated by Django 2.2.13 on 2021-01-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_ticket_inward_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estimation',
            field=models.BooleanField(default=False),
        ),
    ]
