# Generated by Django 2.2.13 on 2021-01-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='gsx_ship_to',
            field=models.CharField(max_length=20),
        ),
    ]
