fail_fast: true
repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v0.9.2
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=500']
    - id: check-byte-order-marker
    - id: fix-encoding-pragma
    - id: end-of-file-fixer
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
    - id: detect-private-key
    - id: flake8
    - id: double-quote-string-fixer
    - id: trailing-whitespace

- repo: local
  hooks:
  - id: missing-migrations
    name: missing-migrations-local
    entry: pipenv run python manage.py has_missing_migrations
    language: system
    always_run: true
    pass_filenames: false

- repo: git://github.com/FalconSocial/pre-commit-python-sorter
  rev: b57843b0b874df1d16eb0bef00b868792cb245c2
  hooks:
    - id: python-import-sorter
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'e0bad18fb4ad66f9cd90660d7a4c74d2a026ab12'  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
