fail_fast: true
repos:
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v0.9.2
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=500']
    - id: check-byte-order-marker
    - id: fix-encoding-pragma
    - id: end-of-file-fixer
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
    - id: detect-private-key
    - id: flake8
    - id: trailing-whitespace

- repo: local
  hooks:
  - id: missing-migrations
    name: missing-migrations-local
    entry: pipenv run python manage.py has_missing_migrations
    language: system
    always_run: true
    pass_filenames: false


-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.3.0
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
