# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-07-01 09:49

import devices.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("devices", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="alternate_device_id",
            field=models.CharField(
                max_length=20,
                null=True,
                validators=[
                    devices.validators.validate_identifier,
                    devices.validators.validate_restricted_device,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="serial_number",
            field=models.CharField(
                max_length=20,
                null=True,
                validators=[
                    devices.validators.validate_identifier,
                    devices.validators.validate_restricted_device,
                ],
            ),
        ),
    ]
