# Generated by Django 2.2.13 on 2020-12-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200701_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gsx_repair_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='gsx_service_non_repair_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
