# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-12-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("devices", "0005_componentissue")]

    operations = [
        migrations.RenameField(
            model_name="componentissue",
            old_name="componenet_code",
            new_name="component_code",
        ),
        migrations.RenameField(
            model_name="componentissue",
            old_name="componenet_description",
            new_name="component_description",
        ),
    ]
