# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-12-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("devices", "0006_auto_20201214_0927")]

    operations = [
        migrations.AddField(
            model_name="componentissue",
            name="reproducibility",
            field=models.CharField(default="A", max_length=100),
            preserve_default=False,
        )
    ]
