# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-09-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tokens", "0003_auto_20200922_1248")]

    operations = [
        migrations.AddField(
            model_name="token",
            name="invite_sent_on",
            field=models.DateTimeField(null=True),
        )
    ]
