# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-09-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tokens", "0004_token_invite_sent_on")]

    operations = [
        migrations.AddField(
            model_name="token",
            name="is_present",
            field=models.BooleanField(default=False),
        )
    ]
