# Generated by Django 2.2.13 on 2020-12-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_token_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
