# Generated by Django 2.2.13 on 2021-01-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0007_auto_20210128_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
