# -*- coding: utf-8 -*-
# Generated by Django 2.2.8 on 2020-04-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gsx_ship_to',
            field=models.CharField(default='0001026647', max_length=100),
        ),
    ]
