# Generated by Django 2.2.13 on 2020-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200728_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SuperUser'), (2, 'Technician'), (3, 'TokenUser'), (4, 'Auditor'), (5, 'Privileged')], default=2),
        ),
    ]
