# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("customers", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="alternate_contact_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        )
    ]
