# -*- coding: utf-8 -*-
# Generated by Django 2.2.13 on 2020-12-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("customers", "0002_customer_alternate_contact_number")]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        )
    ]
