# -*- coding: utf-8 -*-
# Generated by Django 2.2.8 on 2020-04-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200309_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repairinventoryitem',
            options={'ordering': ['-id']},
        ),
    ]
