# Generated by Django 2.2.8 on 2020-02-25 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                ('sla_type', models.CharField(choices=[('TICKET_SLA', 'Ticket SLA'), ('DELIVERY_SLA', 'Delivery SLA'), ('PHONE_LOAN_AGREEMENT', 'Phone Loan Agreement')], default='TICKET_SLA', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sla', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_sla', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SLA',
                'verbose_name_plural': 'SLAs',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                ('statement', models.TextField()),
                ('heading', models.TextField(max_length=2048, null=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_term', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_term', to=settings.AUTH_USER_MODEL)),
                ('sla', models.ManyToManyField(related_name='terms', to='slas.SLA')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
            },
        ),
    ]
