# Generated by Django 2.2.8 on 2020-02-25 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(editable=False, max_length=40)),
                ('version', models.CharField(default='v0', max_length=3)),
                ('value', models.CharField(max_length=100)),
                ('list_name', models.CharField(choices=[('TICKET_STATUS', 'Ticket Status'), ('COVERAGE_TYPE', 'Coverage Type'), ('GSX_SERVICE_TYPE', 'GSX Service Type'), ('REPAIR_TYPE', 'Repair Type'), ('GSX_REPAIR_TYPE', 'GSX Repair Type'), ('CUSTOMER_TYPE', 'Customer Type'), ('UNIT_PART', 'Unit Part'), ('STATES', 'States'), ('COUNTRIES', 'Countries'), ('SERIALIZABLE_INVENTORY_ITEM', 'Serializable Inventory Item'), ('LOANER_INVENTORY_PART_NUMBERS', 'Loaner Inventory Part Numbers'), ('LOANER_INVENTORY_PENALTY_REASONS', 'Loaner Inventory Penalty Reasons')], default='TICKET_STATUS', max_length=100)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_item', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_item', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List Item',
                'verbose_name_plural': 'List Items',
            },
        ),
    ]
